Refactoring monitor external transactions
Revolution-Populi/EES pull request #29
Opened 2023-03-07 08:58 UTC by Griffics

2023-03-09 06:45 UTC, walteratwork requested changes
Fix merge conflicts and make tests work

2023-03-09 06:45 UTC, walteratwork commented on Context/Application/Cli/CliModule.ts
> +export class CliModule {}
No newline at end of file. Check all new files for this issue.

2023-03-09 06:45 UTC, walteratwork commented on Context/Application/Command/ExternalBlockchain/ProcessIncomingContractCreation/ProcessIncomingContractCreation.ts
> +export default class ProcessIncomingContractCreation implements ExternalBlockchainCommandInterface{
Missing space before curly brace. Could we use eslint to handle such issues?

2023-03-09 06:45 UTC, walteratwork commented on Context/Application/Command/ExternalBlockchain/ChainProcessor/ExternalBlockchainCommandInterface.ts
> +}
Why do you assume that all commands will have this data?

2023-03-09 06:45 UTC, walteratwork commented on Context/Application/Command/ExternalBlockchain/ChainProcessor/ExternalBlockchainHandlerInterface.ts
> +    execute(range: BlockRange): Promise<void>
Why do you assume that all command handlers will have an execute method with a range parameter?

2023-03-09 06:45 UTC, walteratwork commented on Context/Application/Command/ExternalBlockchain/ChainProcessor/ExternalBlockchainHandlerInterface.ts
> +
excess line

2023-03-09 06:45 UTC, walteratwork commented on Context/Application/Command/ExternalBlockchain/ProcessIncomingContractCreation/ProcessIncomingContractCreationHandler.ts
> +    async execute(range: BlockRange): Promise<void> {
I prefer the previous version where the command handler receives the command to handle.
This follows the Command pattern.

2023-03-09 09:25 UTC, lunacrafts commented on Context/Application/Command/ExternalBlockchain/ProcessIncomingContractCreation/ProcessIncomingContractCreation.ts
> +export default class ProcessIncomingContractCreation implements ExternalBlockchainCommandInterface{
[editorconfig](https://editorconfig.org/) should work great in this and above case

2023-03-10 12:27 UTC, Griffics commented on Context/Application/Command/ExternalBlockchain/ProcessIncomingContractCreation/ProcessIncomingContractCreation.ts
> +export default class ProcessIncomingContractCreation implements ExternalBlockchainCommandInterface{
> [editorconfig](https://editorconfig.org/) should work great in this and above case

Thank you for interesting idea

2023-03-13 09:15 UTC, walteratwork approved these changes

2023-03-13 09:16 UTC, merged